# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('stats', '0001_initial'), ('stats', '0002_auto_20160609_0726'), ('stats', '0003_remove_instancetest_query')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('hidden_service_url', models.URLField(blank=True)),
                ('install_since', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=1024)),
                ('method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=1024)),
                ('language', models.CharField(blank=True, max_length=1024)),
                ('image_proxy', models.CharField(blank=True, max_length=1024)),
                ('safesearch', models.CharField(blank=True, max_length=1024)),
                ('locale', models.CharField(blank=True, max_length=1024)),
                ('engine', models.ForeignKey(db_column='engine_name', on_delete=django.db.models.deletion.CASCADE, to='stats.Engine')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('response_time', models.DurationField()),
                ('http_result', models.PositiveSmallIntegerField()),
                ('certificate_issuer', models.CharField(blank=True, max_length=1024)),
                ('searx_version', models.CharField(blank=True, max_length=32)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Instance')),
            ],
        ),
    ]
