# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=1024)),
                ('signature_algorithm', models.CharField(blank=True, max_length=256)),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('issuer', models.CharField(blank=True, max_length=1024)),
                ('subject', models.CharField(blank=True, max_length=1024)),
                ('cert', models.CharField(blank=True, max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, unique=True)),
                ('hidden_service_url', models.URLField(blank=True)),
                ('install_since', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InstanceTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pretransfer_response_time', models.DurationField()),
                ('total_response_time', models.DurationField()),
                ('connection_error_message', models.CharField(blank=True, max_length=256)),
                ('valid_ssl', models.BooleanField(default=True)),
                ('http_status_code', models.PositiveSmallIntegerField(null=True)),
                ('valid_instance', models.BooleanField(default=True)),
                ('searx_version', models.CharField(blank=True, max_length=32)),
                ('certificate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Certificate')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Instance')),
            ],
            options={
                'ordering': ['-timestamp', 'instance', 'url'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=1024)),
                ('method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=1024)),
                ('language', models.CharField(blank=True, max_length=1024)),
                ('image_proxy', models.CharField(blank=True, max_length=1024)),
                ('safesearch', models.CharField(blank=True, max_length=1024)),
                ('locale', models.CharField(blank=True, max_length=1024)),
                ('engine', models.ForeignKey(db_column='engine_name', on_delete=django.db.models.deletion.CASCADE, to='stats.Engine')),
            ],
        ),
        migrations.CreateModel(
            name='QueryTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pretransfer_response_time', models.DurationField()),
                ('total_response_time', models.DurationField()),
                ('connection_error_message', models.CharField(blank=True, max_length=256)),
                ('http_status_code', models.PositiveSmallIntegerField()),
                ('valid_result', models.BooleanField(default=True)),
                ('result_count', models.PositiveSmallIntegerField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Instance')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Query')),
            ],
            options={
                'ordering': ['-timestamp', 'instance', 'query'],
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=1024, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='querytest',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Url'),
        ),
        migrations.AddField(
            model_name='instancetest',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Url'),
        ),
        migrations.AlterUniqueTogether(
            name='querytest',
            unique_together=set([('timestamp', 'instance', 'url')]),
        ),
        migrations.AlterUniqueTogether(
            name='instancetest',
            unique_together=set([('timestamp', 'instance', 'url')]),
        ),
    ]
