# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancetest',
            options={},
        ),
        migrations.AddField(
            model_name='instancetest',
            name='aggregate_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
