# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_squashed_0003_remove_instancetest_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancetest',
            name='error_message',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
