# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('response_time', models.DurationField()),
                ('http_result', models.PositiveSmallIntegerField()),
                ('certificate_issuer', models.CharField(blank=True, max_length=1024)),
                ('searx_version', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='enginetest',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='enginetest',
            name='query',
        ),
        migrations.AlterField(
            model_name='instance',
            name='install_since',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='EngineTest',
        ),
        migrations.AddField(
            model_name='instancetest',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Instance'),
        ),
        migrations.AddField(
            model_name='instancetest',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Query'),
        ),
    ]
