# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20160609_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancetest',
            name='query',
        ),
    ]
