# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20160610_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='hidden_service_url',
            field=models.URLField(blank=True),
        ),
    ]
