# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20160610_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=1024)),
                ('signature_algorithm', models.CharField(blank=True, max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('issuer', models.CharField(blank=True, max_length=1024)),
                ('subject', models.CharField(blank=True, max_length=1024)),
                ('cert', models.CharField(blank=True, max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='QueryTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('response_time', models.DurationField()),
                ('http_result', models.PositiveSmallIntegerField()),
                ('error_message', models.CharField(blank=True, max_length=256)),
                ('result_count', models.PositiveSmallIntegerField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Instance')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Query')),
            ],
        ),
        migrations.RemoveField(
            model_name='instancetest',
            name='certificate_issuer',
        ),
        migrations.AddField(
            model_name='instancetest',
            name='certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Certificate'),
        ),
    ]
