# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20160611_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='end_date',
            new_name='expire_date',
        ),
    ]
