# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20160611_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancetest',
            name='valid_instance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instancetest',
            name='valid_ssl',
            field=models.BooleanField(default=True),
        ),
    ]
