#!/bin/sh
set -e

GECKODRIVER_VERSION="v0.37.1"

# skip if version is already on PATH
if geckodriver -V 2>/dev/null | head -n 1 | grep -q "geckodriver ${GECKODRIVER_VERSION#v}"; then
    exit 0
fi

case "$(uname -m)" in
    aarch64) ARCH="linux-aarch64";;
    x86_64) ARCH="linux64";;
    *) echo "Unsupported architecture '$(uname -m)'"; exit 1;;
esac

GECKODRIVER_URL="https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-$ARCH.tar.gz"

if [ -z "$1" ]; then
    if [ -z "$VIRTUAL_ENV" ]; then
        printf "geckodriver can't be installed because VIRTUAL_ENV is not set, you should download it from\n  %s\n" "$GECKODRIVER_URL"
        exit 1
    fi
    GECKODRIVER_DIR="$VIRTUAL_ENV/bin"
else
    GECKODRIVER_DIR="$1"
    mkdir -p -- "$GECKODRIVER_DIR"
fi

printf "Installing %s/geckodriver from\n  %s\n" "$GECKODRIVER_DIR" "$GECKODRIVER_URL"

FILE="`mktemp`"
wget -qO "$FILE" -- "$GECKODRIVER_URL" && tar xz -C "$GECKODRIVER_DIR" -f "$FILE" geckodriver
rm -- "$FILE"
chown "$(id -u):$(id -g)" -- "$GECKODRIVER_DIR/geckodriver"
chmod 755 -- "$GECKODRIVER_DIR/geckodriver"
